### ISSUE TITLE
RC Migration Guide Tracker

### ISSUE THREAD

**Issue by delucis** [withastro/docs#1047]
We’re going to want to document a few things in our migration guide, so I’m using this issue to keep track before we forget. Throw anything else you spot in here!

- [x] If using `<Markdown />`, you need to install `@astrojs/markdown-component` and update your imports (see #1045 and https://github.com/withastro/astro/pull/3986)
- [x] Vite 3 update (done in #1049)
- [x] canonicalURL deprecation (see #1033)
- [x] Current component-in-markdown support will be behind `legacy.astroFlavoredMarkdown` flag (see #1090 https://github.com/withastro/astro/pull/4016)
- [x] New `output` option (see https://github.com/withastro/astro/pull/4015)
- [ ] New `.html` support (see https://github.com/withastro/astro/pull/3867)
- [x] Update `getHeaders()` to `getHeadings()`. Double check if we mentioned `astro.content.headers`
- [ ] Update references to Markdown `content` to use `frontmatter` (when @bholmesdev’s done it!)

**Comment by sarah11918** [comment]
I'm guessing that Ben's `legacy.astroFlavoredMarkdown` PR will need some migration guide content re: no more components, variables etc. in Markdown

https://github.com/withastro/astro/pull/4016

**Comment by sarah11918** [comment]
I did just add RSS feeds are now generated with `@astrojs/rss` to the migration guide.

**Comment by delucis** [comment]
Closing as complete now we have #1418 to track the outstanding task.
