### ISSUE TITLE
Reference generation script improvements

### ISSUE THREAD

**Issue by delucis** [withastro/docs#209]
Suggestions from @FredKSchott for ways to improve the `scripts/docgen.mjs` script that auto-generates the API reference from types in the Astro repo:

- [ ] Instead of `STUB`, take an optional file path to your local `@types/astro.ts` file on disk to test against that. This would save a lot of copy-paste time.

- [x] Adding support for a `@version` JSDoc tag that will automatically add an "Added in: v..." line to the generated Markdown if found. (Done in #215)

- [ ] Adding support to auto-generate CLI flags from that same config, since every CLI flag maps to a configuration option. Right now, the cli-flags.md docs page is still manually maintained, but there's no reason that it couldn't be auto-generated from the same JSDoc (see `@cli --project-root`)

Since then the following ideas have also come up (copied over from #544 — thanks @Chrissdroid!):

- [x] Convert `https://docs.astro.build/` URLS to relative links (Done in #755)

- [x] Add a CI script to run `scripts/docgen.mjs` on a 24 or 48h schedule and auto-update `configuration-reference.md` (Done in #755)

**Comment by sarah11918** [comment]
I assigned this to you @delucis so it would show up on your tracker, and you can triage it from there! Are we still considering these items? Are they for this sprint! Only your tracker knows.... 😄

**Comment by delucis** [comment]
The first of these is maybe not that useful. Auto generating CLI docs seems potentially interesting but not a high priority especially now things are changing less frequently, so I think I'll close this one and we can reconsider if something makes us think we want that.
