### ISSUE TITLE
i18n(fr): I would like to translate all the parts of `fr/guides/deploy/*`

### ISSUE THREAD

**Issue by thomasbnt** [withastro/docs#4984]
This is an issue tracker, I would like to contribute to the French documentation for all the part of `fr/guides/deploy/*`.
Some PRs are already open.
Please assign to me 🚀

TODO : 

```[tasklist]
### Tasks
- [x] https://github.com/withastro/docs/pull/4978
- [x] https://github.com/withastro/docs/pull/4970
- [x] https://github.com/withastro/docs/pull/4976
- [x] https://github.com/withastro/docs/pull/4972
- [x] https://github.com/withastro/docs/pull/4975
- [x] https://github.com/withastro/docs/pull/5033
- [ ] https://github.com/withastro/docs/pull/5124
- [x] https://github.com/withastro/docs/pull/5125
- [ ] https://github.com/withastro/docs/pull/5136
- [ ] https://github.com/withastro/docs/pull/5137
- [ ] https://github.com/withastro/docs/pull/5139
- [ ] https://github.com/withastro/docs/pull/5140
- [ ] https://github.com/withastro/docs/pull/5141
- [ ] https://github.com/withastro/docs/pull/5142
```

**Comment by thomasbnt** [comment]
PRs already open and waiting to review and merged: 
- https://github.com/withastro/docs/pull/4970
- https://github.com/withastro/docs/pull/4978
- https://github.com/withastro/docs/pull/4976
- https://github.com/withastro/docs/pull/4972

**Comment by thomasbnt** [comment]
- `deploy/google-firebase` by https://github.com/withastro/docs/pull/4953 (not me)

**Comment by thomasbnt** [comment]
All are merged. 🚀🎃
