### ISSUE TITLE
i18n(fr) : Translating all `guides/integrations-guide/*` in French language

### ISSUE THREAD

**Issue by thomasbnt** [withastro/docs#6052]
### 📋 Explain your issue

I would like to translate all files in `guides/integrations-guide/*` in French language. This list will be updated with PR linked.
This is a little challenge of the month, contribute more and finish this part.
```[tasklist]
### Tasks
- [ ] https://github.com/withastro/docs/pull/6060
- [ ] https://github.com/withastro/docs/pull/6061
- [ ] https://github.com/withastro/docs/pull/6078
- [ ] https://github.com/withastro/docs/pull/6080
- [ ] https://github.com/withastro/docs/pull/6125
- [ ] https://github.com/withastro/docs/pull/6126
- [ ] https://github.com/withastro/docs/pull/6165
- [ ] https://github.com/withastro/docs/pull/6166
- [ ] https://github.com/withastro/docs/pull/6173
- [ ] https://github.com/withastro/docs/pull/6174
- [ ] https://github.com/withastro/docs/pull/6190
- [ ] https://github.com/withastro/docs/pull/6191
- [ ] https://github.com/withastro/docs/pull/6203
- [ ] https://github.com/withastro/docs/pull/6204
- [ ] https://github.com/withastro/docs/pull/6230
- [ ] https://github.com/withastro/docs/pull/6231
- [ ] https://github.com/withastro/docs/pull/6232
```

**Comment by thomasbnt** [comment]
After completed that, I will update some files.

![diska](https://github.com/withastro/docs/assets/14293805/516a540e-71c5-4103-a1ae-039619688a32)
